global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['traefik:80']
    metrics_path: /metrics