version: '3'

services:
  astroluma:
    image: ghcr.io/astroluma/astroluma:latest
    container_name: astroluma
    restart: unless-stopped
    volumes:
      - ../data/astroluma:/app/data
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astroluma.rule=Host(`dashboard.${DOMAIN}`)"
      - "traefik.http.routers.astroluma.entrypoints=websecure"
      - "traefik.http.routers.astroluma.tls=true"
      - "traefik.http.services.astroluma.loadbalancer.server.port=${ASTROLUMA_PORT}"

networks:
  traefik_network:
    external: true
