services:
  mongodb:
    image: mongo:latest
    container_name: astroluma_mongodb
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${MONGODB_MEMORY_LIMIT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=astroluma
    volumes:
      - ../data/mongodb:/data/db
    networks:
      - astroluma_network
    ports:
      - "127.0.0.1:${MONGODB_HOST_PORT}:${MONGODB_CONTAINER_PORT}"

  app:
    image: sanjeet990/astroluma:latest
    container_name: astroluma
    restart: unless-stopped
    ports:
      - "${LUMA_PORT}"
    deploy:
      resources:
        limits:
          memory: ${LUMA_MEMORY_LIMIT}
    environment:
      - MONGODB_URI=mongodb://admin:${MONGODB_PASSWORD}@mongodb:${MONGODB_CONTAINER_PORT}/astroluma?authSource=admin
      - NODE_ENV=production
    volumes:
      - ../data/astroluma:/app/data
    networks:
      - traefik_network:
          external: true
      - astroluma_network:
          driver: bridge
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astroluma.rule=Host(`${LUMA_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.astroluma.entrypoints=websecure"
      - "traefik.http.routers.astroluma.tls=true"
      - "traefik.http.services.astroluma.loadbalancer.server.port=${LUMA_CONTAINER_PORT}"