services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT}"
    deploy:
      resources:
        limits:
          memory: ${N8N_MEMORY_LIMIT}
    environment:
      - N8N_HOST=${N8N_SUBDOMAIN}.${DOMAIN}
      - N8N_PROTOCOL=https
      - N8N_PORT=${N8N_CONTAINER_PORT}
      - N8N_EDITOR_BASE_URL=https://${N8N_SUBDOMAIN}.${DOMAIN}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=${POSTGRES_CONTAINER_PORT}
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - WEBHOOK_URL=https://${N8N_SUBDOMAIN}.${DOMAIN}/
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_RUNNERS_ENABLED=true
      # Ollama integration
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
    volumes:
      - ../data/n8n:/home/node/.n8n
      - ../shared:/data/shared
    networks:
      - ${TRAEFIK_NETWORK}
      - n8n_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=${N8N_CONTAINER_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEMORY_LIMIT}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=n8n
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - n8n_network
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"

networks:
  ${TRAEFIK_NETWORK}:
    external: true
  n8n_network:
    driver: bridge