version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HOST_PORT_HTTP}:80"
      - "${TRAEFIK_HOST_PORT_HTTPS}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../config/traefik:/etc/traefik
      - ../config/traefik/certs:/certs
    networks:
      - traefik_network
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:${TRAEFIK_CONTAINER_PORT_HTTP}"
      - "--entrypoints.websecure.address=:${TRAEFIK_CONTAINER_PORT_HTTPS}"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=${TRAEFIK_DASHBOARD_PORT}"

networks:
  traefik_network:
    external: true
